# Generated by Django 3.2.20 on 2023-08-20 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20230820_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='image',
            new_name='profile_picture',
        ),
    ]
