# Generated by Django 3.2.20 on 2023-08-24 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
    ]
